#!/bin/bash

function install_node_version_manager {
    # Repo https://github.com/nvm-sh/nvm
    echo_message title "Running 'install_node_version_manager' function"
    check_install_apt_package curl
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    NVM_EXPORT='export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'

    if [ ! -f ~/.zshrc ]; then
        echo_message warning "No .zshrc file found. Adding node version manager to bashrc"
    else
        echo_message info "Zshrc found, adding node version manager"
        echo $NVM_EXPORT >> ~/.zshrc
    fi
}
